"""create new tables

Revision ID: fc928bc2569e
Revises: 
Create Date: 2024-12-18 14:59:49.837676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc928bc2569e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_items')
    op.drop_table('message')
    op.drop_table('occupancy_rate')
    op.drop_table('categories')
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('hotels')
    op.drop_table('reservation')
    op.drop_table('payments')
    op.drop_table('report')
    op.drop_table('booking_source')
    op.drop_table('rooms')
    op.drop_table('guests')
    op.drop_table('staff')
    op.drop_table('notifications')
    op.drop_table('orders')
    op.drop_table('bookings')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('invoice_number')

    op.drop_table('invoices')
    op.drop_table('hotel_revenue')
    # Drop foreign key constraint first
    op.execute('ALTER TABLE notifications DROP FOREIGN KEY notifications_ibfk_1')

    # Then drop the hotels table
    op.drop_table('hotels')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_revenue',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('rooms_revenue', mysql.FLOAT(), nullable=False),
    sa.Column('food_beverages_revenue', mysql.FLOAT(), nullable=False),
    sa.Column('telephone_revenue', mysql.FLOAT(), nullable=False),
    sa.Column('other_revenue', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('invoices',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guest_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('invoice_date', sa.DATE(), nullable=False),
    sa.Column('invoice_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.ENUM('expectant', 'paid'), nullable=False),
    sa.Column('net_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('gross_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name='invoices_ibfk_1'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='invoices_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('invoice_number', ['invoice_number'], unique=True)

    op.create_table('bookings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guest_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_in_date', sa.DATE(), nullable=False),
    sa.Column('check_out_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name='bookings_ibfk_1'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='bookings_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('guest_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('delivery_details', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('vat', mysql.FLOAT(), nullable=True),
    sa.Column('total', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notifications',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='notifications_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('staff',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('shift', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('joining_date', mysql.DATETIME(), nullable=True),
    sa.Column('salary', mysql.FLOAT(), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('middle_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('id_card_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('id_card_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('contact_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('residence', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('shift_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('next_of_kin_first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('next_of_kin_last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('next_of_kin_relation', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('next_of_kin_contact_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('next_of_kin_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('next_of_kin_residence', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('guests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('nationality', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('language', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('guest_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('zip_code', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('id_card_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_card_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('rooms',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_type', mysql.ENUM('Single', 'Double', 'Suite', 'Family'), nullable=False),
    sa.Column('room_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('is_available', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('booking_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('housekeeping_status', mysql.ENUM('clean', 'cleaning_in_progress', 'dirty', 'out_of_service'), nullable=False),
    sa.Column('priority', mysql.ENUM('high', 'low'), nullable=True),
    sa.Column('reservation_status', mysql.ENUM('due_in', 'checked_in', 'due_out'), nullable=True),
    sa.Column('comments', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='rooms_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('booking_source',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('online_channel', mysql.FLOAT(), nullable=False),
    sa.Column('offline_channel', mysql.FLOAT(), nullable=False),
    sa.Column('repeat_clients', mysql.FLOAT(), nullable=False),
    sa.Column('website_channel', mysql.FLOAT(), nullable=False),
    sa.Column('referrals', mysql.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('report',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_revenue', mysql.FLOAT(), nullable=False),
    sa.Column('total_expenses', mysql.FLOAT(), nullable=False),
    sa.Column('total_profit', mysql.FLOAT(), nullable=False),
    sa.Column('report_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_on', mysql.DATETIME(), nullable=True),
    sa.Column('data', mysql.JSON(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='report_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('guest_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_due', mysql.FLOAT(), nullable=False),
    sa.Column('amount_paid', mysql.FLOAT(), nullable=True),
    sa.Column('pending_amount', mysql.FLOAT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name='payments_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('reservation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('room_number', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('check_in_date', sa.DATE(), nullable=False),
    sa.Column('check_out_date', sa.DATE(), nullable=False),
    sa.Column('no_of_rooms', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('no_of_adults', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('no_of_children', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('home_address', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('telephone', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hotels',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('total_rooms', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revenue_generated', mysql.FLOAT(), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('hotels', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('categories',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('vat_percentage', mysql.FLOAT(), nullable=True),
    sa.Column('has_delivery', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('delivery_fee', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('occupancy_rate',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('occupancy_rate', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('message',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('channel_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_type', mysql.ENUM('employee', 'guest'), nullable=True),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('invoice_items',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('net_amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('vat_percentage', mysql.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('discount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='invoice_items_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
